#!/usr/bin/env python3
"""Generate a clean, data-driven Mermaid language pie chart in README.md."""
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(ROOT, "docs", "data", "stats.json")
README = os.path.join(ROOT, "README.md")

START = "<!-- LANGUAGE_ANALYTICS_START -->"
END = "<!-- LANGUAGE_ANALYTICS_END -->"


def main():
    with open(DATA, encoding="utf-8") as handle:
        data = json.load(handle)

    languages = [
        item for item in data.get("languages", [])
        if item.get("name") and item.get("bytes", 0) > 0
    ]
    languages.sort(key=lambda item: item["bytes"], reverse=True)

    total = sum(item["bytes"] for item in languages) or 1
    top = languages[:6]
    other_bytes = total - sum(item["bytes"] for item in top)

    lines = [
        START,
        "### Language Distribution",
        "",
        "```mermaid",
        "pie showData",
        "    title GitHub Language Distribution",
    ]

    for item in top:
        percent = item["bytes"] / total * 100
        lines.append(f'    "{item["name"]}" : {percent:.2f}')

    if other_bytes > 0:
        lines.append(f'    "Other" : {other_bytes / total * 100:.2f}')

    lines.extend([
        "```",
        "",
        "_Live repository language data · generated by Python_",
        END,
    ])
    block = "\n".join(lines)

    with open(README, encoding="utf-8") as handle:
        readme = handle.read()

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(readme):
        raise RuntimeError("Language Analytics markers not found in README.md")

    readme = pattern.sub(block, readme, count=1)

    with open(README, "w", encoding="utf-8") as handle:
        handle.write(readme)


if __name__ == "__main__":
    main()
