#!/usr/bin/env python3
"""Generate a native GitHub README vertical language chart from repository data."""
import json
import os
import re
import html

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(ROOT, "docs", "data", "stats.json")
README = os.path.join(ROOT, "README.md")

START = "<!-- LANGUAGE_ANALYTICS_START -->"
END = "<!-- LANGUAGE_ANALYTICS_END -->"

COLORS = [
    "#FFB02E", "#2F9BF4", "#8B68F5", "#39C98A",
    "#F06B78", "#20C4E8", "#9AA9BC"
]


def main():
    with open(DATA, encoding="utf-8") as handle:
        data = json.load(handle)

    languages = [
        item for item in data.get("languages", [])
        if item.get("name") and item.get("bytes", 0) > 0
    ]
    languages.sort(key=lambda item: item["bytes"], reverse=True)

    total = sum(item["bytes"] for item in languages) or 1
    top = languages[:7]
    rows = []
    percentages = []

    for item in top:
        percent = item["bytes"] / total * 100
        percentages.append(percent)

    lines = [
        START,
        '<div align="center">',
        '',
        '<h2>Language Analytics</h2>',
        '',
        '<strong>Repository Language Breakdown</strong>',
        '',
        '<table width="100%" border="0" cellspacing="0" cellpadding="3">',
        '<tr>' + ''.join(f'<td align="center"><strong>{percent:.2f}%</strong></td>' for percent in percentages) + '</tr>',
    ]

    # Ten 5%-high cells create a true vertical bar chart without Mermaid controls.
    for level in range(50, 0, -5):
        cells = []
        for index, percent in enumerate(percentages):
            filled = percent >= level
            if filled:
                cells.append(f'<td align="center"><font color="{COLORS[index]}">█</font></td>')
            else:
                cells.append('<td align="center">&nbsp;</td>')
        lines.append('<tr>' + ''.join(cells) + '</tr>')

    lines.extend([
        '</table>',
        '',
        '<table width="100%" border="0" cellspacing="0" cellpadding="2">',
        '<tr>' + ''.join(f'<td align="center"><font color="{COLORS[index]}">●</font></td>' for index in range(len(top))) + '</tr>',
        '<tr>' + ''.join(f'<td align="center"><strong>{html.escape(item["name"])}</strong></td>' for item in top) + '</tr>',
        '</table>',
        '',
        '<strong>Usage (%)</strong> · 0 — 50',
        '',
        '<sub>🟢 Live Data · Updated every 6 hours</sub>',
        '',
        '<em>Live repository language data · generated by Python</em>',
        '',
        '</div>',
        END,
    ])

    block = "\n".join(lines)

    with open(README, encoding="utf-8") as handle:
        readme = handle.read()

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(readme):
        raise RuntimeError("Language Analytics markers not found in README.md")

    readme = pattern.sub(block, readme, count=1)

    with open(README, "w", encoding="utf-8") as handle:
        handle.write(readme)


if __name__ == "__main__":
    main()
