#!/usr/bin/env python3
"""Generate a premium, data-driven language analytics SVG for the profile README."""
import json
import os
import html

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(ROOT, "docs", "data", "stats.json")
OUTPUT = os.path.join(ROOT, "assets", "language-analytics.svg")

COLORS = ["#FFB52E", "#2F9BF4", "#8B68F5", "#39C98A", "#F06B78", "#20C4E8", "#9AA9BC"]


def main():
    with open(DATA, encoding="utf-8") as handle:
        data = json.load(handle)

    languages = [x for x in data.get("languages", []) if x.get("name") and x.get("bytes", 0) > 0]
    languages.sort(key=lambda x: x["bytes"], reverse=True)
    total = sum(x["bytes"] for x in languages) or 1
    top = languages[:6]
    other_bytes = total - sum(x["bytes"] for x in top)
    items = [(x["name"], x["bytes"] / total * 100) for x in top]
    if other_bytes > 0:
        items.append(("Other", other_bytes / total * 100))

    width, height = 1200, 650
    left, right, top_y, bottom = 105, 1125, 150, 505
    chart_h = bottom - top_y
    slot = (right - left) / len(items)
    bar_w = min(112, slot * 0.58)
    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
        '<title id="title">Language Analytics — Repository Language Breakdown</title>',
        '<desc id="desc">Dynamically generated repository language usage chart.</desc>',
        '<defs>',
        '<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0A1118"/><stop offset="1" stop-color="#071017"/></linearGradient>',
        '<filter id="soft" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>',
        '</defs>',
        '<rect x="10" y="10" width="1180" height="630" rx="18" fill="url(#bg)" stroke="#243541"/>',
        '<rect x="11" y="11" width="1178" height="628" rx="17" fill="none" stroke="#13212B"/>',
        '<g font-family="Inter,Segoe UI,Arial,sans-serif">',
        '<text x="62" y="70" font-size="34" font-weight="700" fill="#F2F6FA">Language <tspan fill="#2FD9E8">Analytics</tspan></text>',
        '<text x="62" y="104" font-size="20" fill="#91A4B7">Repository Language Breakdown</text>',
        '<g transform="translate(1000 52)"><rect width="142" height="38" rx="19" fill="#071D1A" stroke="#126D61"/><circle cx="20" cy="19" r="7" fill="#31E6B4"/><text x="37" y="25" font-size="15" fill="#31E6B4">Live Data</text></g>',
        '<text x="1140" y="112" text-anchor="end" font-size="13" fill="#91A4B7">Updated every 6 hours</text>',
        '<text x="62" y="178" font-size="14" font-weight="600" fill="#AFC0CF">USAGE (%)</text>',
    ]

    for tick in range(0, 51, 10):
        y = bottom - chart_h * tick / 50
        svg.append(f'<line x1="{left}" y1="{y:.1f}" x2="{right}" y2="{y:.1f}" stroke="#263642" stroke-dasharray="5 7"/>')
        svg.append(f'<text x="{left-18}" y="{y+5:.1f}" text-anchor="end" font-size="14" fill="#A9B8C7">{tick}</text>')

    svg.append(f'<line x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}" stroke="#526A7A"/>')

    for i, (name, pct) in enumerate(items):
        cx = left + slot * (i + 0.5)
        h = chart_h * min(pct, 50) / 50
        x = cx - bar_w / 2
        y = bottom - h
        color = COLORS[i]
        svg.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{h:.1f}" rx="3" fill="{color}" opacity="0.96"/>')
        svg.append(f'<text x="{cx:.1f}" y="{max(y-14, 196):.1f}" text-anchor="middle" font-size="18" font-weight="700" fill="{color}">{pct:.2f}%</text>')
        # Small language mark beneath each bar; intentionally vector-only/no external assets.
        mark = {"Java":"☕", "TypeScript":"TS", "C":"C", "Rust":"R", "Python":"Py", "CMake":"◆", "Other":"•••"}.get(name, name[:2])
        svg.append(f'<text x="{cx:.1f}" y="548" text-anchor="middle" font-size="20" font-weight="700" fill="{color}">{html.escape(mark)}</text>')
        svg.append(f'<text x="{cx:.1f}" y="579" text-anchor="middle" font-size="15" fill="#DCE6EE">{html.escape(name)}</text>')

    svg.extend([
        '<circle cx="63" cy="607" r="9" fill="none" stroke="#2F9BF4" stroke-width="2"/>',
        '<text x="63" y="612" text-anchor="middle" font-size="12" font-weight="700" fill="#2F9BF4">i</text>',
        '<text x="82" y="612" font-size="14" font-style="italic" fill="#91A4B7">Live repository language data · generated by Python</text>',
        '</g></svg>',
    ])

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(svg) + "\n")


if __name__ == "__main__":
    main()
